struct tz_unicode_mapping {const char *other; const char* territory; const char* type;};
const struct tz_unicode_mapping tz_unicode_map[] = {
//Generated from windowsZones.xml
//Obtained from local file
{"Dateline Standard Time", "001", "Etc/GMT+12"},
{"Dateline Standard Time", "ZZ", "Etc/GMT+12"},
{"UTC-11", "001", "Etc/GMT+11"},
{"UTC-11", "AS", "Pacific/Pago_Pago"},
{"UTC-11", "NU", "Pacific/Niue"},
{"UTC-11", "UM", "Pacific/Midway"},
{"UTC-11", "ZZ", "Etc/GMT+11"},
{"Hawaiian Standard Time", "001", "Pacific/Honolulu"},
{"Hawaiian Standard Time", "CK", "Pacific/Rarotonga"},
{"Hawaiian Standard Time", "PF", "Pacific/Tahiti"},
{"Hawaiian Standard Time", "UM", "Pacific/Johnston"},
{"Hawaiian Standard Time", "US", "Pacific/Honolulu"},
{"Hawaiian Standard Time", "ZZ", "Etc/GMT+10"},
{"Alaskan Standard Time", "001", "America/Anchorage"},
{"Alaskan Standard Time", "US", "America/Anchorage"},
{"Alaskan Standard Time", "US", "America/Juneau"},
{"Alaskan Standard Time", "US", "America/Nome"},
{"Alaskan Standard Time", "US", "America/Sitka"},
{"Alaskan Standard Time", "US", "America/Yakutat"},
{"Pacific Standard Time (Mexico)", "001", "America/Santa_Isabel"},
{"Pacific Standard Time (Mexico)", "MX", "America/Santa_Isabel"},
{"Pacific Standard Time", "001", "America/Los_Angeles"},
{"Pacific Standard Time", "CA", "America/Vancouver"},
{"Pacific Standard Time", "CA", "America/Dawson"},
{"Pacific Standard Time", "CA", "America/Whitehorse"},
{"Pacific Standard Time", "MX", "America/Tijuana"},
{"Pacific Standard Time", "US", "America/Los_Angeles"},
{"Pacific Standard Time", "ZZ", "PST8PDT"},
{"US Mountain Standard Time", "001", "America/Phoenix"},
{"US Mountain Standard Time", "CA", "America/Dawson_Creek"},
{"US Mountain Standard Time", "CA", "America/Creston"},
{"US Mountain Standard Time", "MX", "America/Hermosillo"},
{"US Mountain Standard Time", "US", "America/Phoenix"},
{"US Mountain Standard Time", "ZZ", "Etc/GMT+7"},
{"Mountain Standard Time (Mexico)", "001", "America/Chihuahua"},
{"Mountain Standard Time (Mexico)", "MX", "America/Chihuahua"},
{"Mountain Standard Time (Mexico)", "MX", "America/Mazatlan"},
{"Mountain Standard Time", "001", "America/Denver"},
{"Mountain Standard Time", "CA", "America/Edmonton"},
{"Mountain Standard Time", "CA", "America/Cambridge_Bay"},
{"Mountain Standard Time", "CA", "America/Inuvik"},
{"Mountain Standard Time", "CA", "America/Yellowknife"},
{"Mountain Standard Time", "MX", "America/Ojinaga"},
{"Mountain Standard Time", "US", "America/Denver"},
{"Mountain Standard Time", "US", "America/Boise"},
{"Mountain Standard Time", "US", "America/Shiprock"},
{"Mountain Standard Time", "ZZ", "MST7MDT"},
{"Central America Standard Time", "001", "America/Guatemala"},
{"Central America Standard Time", "BZ", "America/Belize"},
{"Central America Standard Time", "CR", "America/Costa_Rica"},
{"Central America Standard Time", "EC", "Pacific/Galapagos"},
{"Central America Standard Time", "GT", "America/Guatemala"},
{"Central America Standard Time", "HN", "America/Tegucigalpa"},
{"Central America Standard Time", "NI", "America/Managua"},
{"Central America Standard Time", "SV", "America/El_Salvador"},
{"Central America Standard Time", "ZZ", "Etc/GMT+6"},
{"Central Standard Time", "001", "America/Chicago"},
{"Central Standard Time", "CA", "America/Winnipeg"},
{"Central Standard Time", "CA", "America/Rainy_River"},
{"Central Standard Time", "CA", "America/Rankin_Inlet"},
{"Central Standard Time", "CA", "America/Resolute"},
{"Central Standard Time", "MX", "America/Matamoros"},
{"Central Standard Time", "US", "America/Chicago"},
{"Central Standard Time", "US", "America/Indiana/Knox"},
{"Central Standard Time", "US", "America/Indiana/Tell_City"},
{"Central Standard Time", "US", "America/Menominee"},
{"Central Standard Time", "US", "America/North_Dakota/Beulah"},
{"Central Standard Time", "US", "America/North_Dakota/Center"},
{"Central Standard Time", "US", "America/North_Dakota/New_Salem"},
{"Central Standard Time", "ZZ", "CST6CDT"},
{"Central Standard Time (Mexico)", "001", "America/Mexico_City"},
{"Central Standard Time (Mexico)", "MX", "America/Mexico_City"},
{"Central Standard Time (Mexico)", "MX", "America/Bahia_Banderas"},
{"Central Standard Time (Mexico)", "MX", "America/Cancun"},
{"Central Standard Time (Mexico)", "MX", "America/Merida"},
{"Central Standard Time (Mexico)", "MX", "America/Monterrey"},
{"Canada Central Standard Time", "001", "America/Regina"},
{"Canada Central Standard Time", "CA", "America/Regina"},
{"Canada Central Standard Time", "CA", "America/Swift_Current"},
{"SA Pacific Standard Time", "001", "America/Bogota"},
{"SA Pacific Standard Time", "CA", "America/Coral_Harbour"},
{"SA Pacific Standard Time", "CO", "America/Bogota"},
{"SA Pacific Standard Time", "EC", "America/Guayaquil"},
{"SA Pacific Standard Time", "HT", "America/Port-au-Prince"},
{"SA Pacific Standard Time", "JM", "America/Jamaica"},
{"SA Pacific Standard Time", "KY", "America/Cayman"},
{"SA Pacific Standard Time", "PA", "America/Panama"},
{"SA Pacific Standard Time", "PE", "America/Lima"},
{"SA Pacific Standard Time", "ZZ", "Etc/GMT+5"},
{"Eastern Standard Time", "001", "America/New_York"},
{"Eastern Standard Time", "BS", "America/Nassau"},
{"Eastern Standard Time", "CA", "America/Toronto"},
{"Eastern Standard Time", "CA", "America/Iqaluit"},
{"Eastern Standard Time", "CA", "America/Montreal"},
{"Eastern Standard Time", "CA", "America/Nipigon"},
{"Eastern Standard Time", "CA", "America/Pangnirtung"},
{"Eastern Standard Time", "CA", "America/Thunder_Bay"},
{"Eastern Standard Time", "TC", "America/Grand_Turk"},
{"Eastern Standard Time", "US", "America/New_York"},
{"Eastern Standard Time", "US", "America/Detroit"},
{"Eastern Standard Time", "US", "America/Indiana/Petersburg"},
{"Eastern Standard Time", "US", "America/Indiana/Vincennes"},
{"Eastern Standard Time", "US", "America/Indiana/Winamac"},
{"Eastern Standard Time", "US", "America/Kentucky/Monticello"},
{"Eastern Standard Time", "US", "America/Louisville"},
{"Eastern Standard Time", "ZZ", "EST5EDT"},
{"US Eastern Standard Time", "001", "America/Indianapolis"},
{"US Eastern Standard Time", "US", "America/Indianapolis"},
{"US Eastern Standard Time", "US", "America/Indiana/Marengo"},
{"US Eastern Standard Time", "US", "America/Indiana/Vevay"},
{"Venezuela Standard Time", "001", "America/Caracas"},
{"Venezuela Standard Time", "VE", "America/Caracas"},
{"Paraguay Standard Time", "001", "America/Asuncion"},
{"Paraguay Standard Time", "PY", "America/Asuncion"},
{"Atlantic Standard Time", "001", "America/Halifax"},
{"Atlantic Standard Time", "BM", "Atlantic/Bermuda"},
{"Atlantic Standard Time", "CA", "America/Halifax"},
{"Atlantic Standard Time", "CA", "America/Glace_Bay"},
{"Atlantic Standard Time", "CA", "America/Goose_Bay"},
{"Atlantic Standard Time", "CA", "America/Moncton"},
{"Atlantic Standard Time", "GL", "America/Thule"},
{"Central Brazilian Standard Time", "001", "America/Cuiaba"},
{"Central Brazilian Standard Time", "BR", "America/Cuiaba"},
{"Central Brazilian Standard Time", "BR", "America/Campo_Grande"},
{"SA Western Standard Time", "001", "America/La_Paz"},
{"SA Western Standard Time", "AG", "America/Antigua"},
{"SA Western Standard Time", "AI", "America/Anguilla"},
{"SA Western Standard Time", "AW", "America/Aruba"},
{"SA Western Standard Time", "BB", "America/Barbados"},
{"SA Western Standard Time", "BL", "America/St_Barthelemy"},
{"SA Western Standard Time", "BO", "America/La_Paz"},
{"SA Western Standard Time", "BQ", "America/Kralendijk"},
{"SA Western Standard Time", "BR", "America/Manaus"},
{"SA Western Standard Time", "BR", "America/Boa_Vista"},
{"SA Western Standard Time", "BR", "America/Eirunepe"},
{"SA Western Standard Time", "BR", "America/Porto_Velho"},
{"SA Western Standard Time", "BR", "America/Rio_Branco"},
{"SA Western Standard Time", "CA", "America/Blanc-Sablon"},
{"SA Western Standard Time", "CW", "America/Curacao"},
{"SA Western Standard Time", "DM", "America/Dominica"},
{"SA Western Standard Time", "DO", "America/Santo_Domingo"},
{"SA Western Standard Time", "GD", "America/Grenada"},
{"SA Western Standard Time", "GP", "America/Guadeloupe"},
{"SA Western Standard Time", "GY", "America/Guyana"},
{"SA Western Standard Time", "KN", "America/St_Kitts"},
{"SA Western Standard Time", "LC", "America/St_Lucia"},
{"SA Western Standard Time", "MF", "America/Marigot"},
{"SA Western Standard Time", "MQ", "America/Martinique"},
{"SA Western Standard Time", "MS", "America/Montserrat"},
{"SA Western Standard Time", "PR", "America/Puerto_Rico"},
{"SA Western Standard Time", "SX", "America/Lower_Princes"},
{"SA Western Standard Time", "TT", "America/Port_of_Spain"},
{"SA Western Standard Time", "VC", "America/St_Vincent"},
{"SA Western Standard Time", "VG", "America/Tortola"},
{"SA Western Standard Time", "VI", "America/St_Thomas"},
{"SA Western Standard Time", "ZZ", "Etc/GMT+4"},
{"Pacific SA Standard Time", "001", "America/Santiago"},
{"Pacific SA Standard Time", "AQ", "Antarctica/Palmer"},
{"Pacific SA Standard Time", "CL", "America/Santiago"},
{"Newfoundland Standard Time", "001", "America/St_Johns"},
{"Newfoundland Standard Time", "CA", "America/St_Johns"},
{"E. South America Standard Time", "001", "America/Sao_Paulo"},
{"E. South America Standard Time", "BR", "America/Sao_Paulo"},
{"E. South America Standard Time", "BR", "America/Araguaina"},
{"Argentina Standard Time", "001", "America/Buenos_Aires"},
{"Argentina Standard Time", "AR", "America/Buenos_Aires"},
{"Argentina Standard Time", "AR", "America/Argentina/La_Rioja"},
{"Argentina Standard Time", "AR", "America/Argentina/Rio_Gallegos"},
{"Argentina Standard Time", "AR", "America/Argentina/Salta"},
{"Argentina Standard Time", "AR", "America/Argentina/San_Juan"},
{"Argentina Standard Time", "AR", "America/Argentina/San_Luis"},
{"Argentina Standard Time", "AR", "America/Argentina/Tucuman"},
{"Argentina Standard Time", "AR", "America/Argentina/Ushuaia"},
{"Argentina Standard Time", "AR", "America/Catamarca"},
{"Argentina Standard Time", "AR", "America/Cordoba"},
{"Argentina Standard Time", "AR", "America/Jujuy"},
{"Argentina Standard Time", "AR", "America/Mendoza"},
{"SA Eastern Standard Time", "001", "America/Cayenne"},
{"SA Eastern Standard Time", "AQ", "Antarctica/Rothera"},
{"SA Eastern Standard Time", "BR", "America/Fortaleza"},
{"SA Eastern Standard Time", "BR", "America/Belem"},
{"SA Eastern Standard Time", "BR", "America/Maceio"},
{"SA Eastern Standard Time", "BR", "America/Recife"},
{"SA Eastern Standard Time", "BR", "America/Santarem"},
{"SA Eastern Standard Time", "FK", "Atlantic/Stanley"},
{"SA Eastern Standard Time", "GF", "America/Cayenne"},
{"SA Eastern Standard Time", "SR", "America/Paramaribo"},
{"SA Eastern Standard Time", "ZZ", "Etc/GMT+3"},
{"Greenland Standard Time", "001", "America/Godthab"},
{"Greenland Standard Time", "GL", "America/Godthab"},
{"Montevideo Standard Time", "001", "America/Montevideo"},
{"Montevideo Standard Time", "UY", "America/Montevideo"},
{"Bahia Standard Time", "001", "America/Bahia"},
{"Bahia Standard Time", "BR", "America/Bahia"},
{"UTC-02", "001", "Etc/GMT+2"},
{"UTC-02", "BR", "America/Noronha"},
{"UTC-02", "GS", "Atlantic/South_Georgia"},
{"UTC-02", "ZZ", "Etc/GMT+2"},
{"Azores Standard Time", "001", "Atlantic/Azores"},
{"Azores Standard Time", "GL", "America/Scoresbysund"},
{"Azores Standard Time", "PT", "Atlantic/Azores"},
{"Cape Verde Standard Time", "001", "Atlantic/Cape_Verde"},
{"Cape Verde Standard Time", "CV", "Atlantic/Cape_Verde"},
{"Cape Verde Standard Time", "ZZ", "Etc/GMT+1"},
{"Morocco Standard Time", "001", "Africa/Casablanca"},
{"Morocco Standard Time", "MA", "Africa/Casablanca"},
{"UTC", "001", "Etc/GMT"},
{"UTC", "001", "Etc/UTC"},
{"UTC", "GL", "America/Danmarkshavn"},
{"UTC", "ZZ", "Etc/GMT"},
{"GMT Standard Time", "001", "Europe/London"},
{"GMT Standard Time", "ES", "Atlantic/Canary"},
{"GMT Standard Time", "FO", "Atlantic/Faeroe"},
{"GMT Standard Time", "GB", "Europe/London"},
{"GMT Standard Time", "GG", "Europe/Guernsey"},
{"GMT Standard Time", "IE", "Europe/Dublin"},
{"GMT Standard Time", "IM", "Europe/Isle_of_Man"},
{"GMT Standard Time", "JE", "Europe/Jersey"},
{"GMT Standard Time", "PT", "Europe/Lisbon"},
{"GMT Standard Time", "PT", "Atlantic/Madeira"},
{"Greenwich Standard Time", "001", "Atlantic/Reykjavik"},
{"Greenwich Standard Time", "BF", "Africa/Ouagadougou"},
{"Greenwich Standard Time", "CI", "Africa/Abidjan"},
{"Greenwich Standard Time", "EH", "Africa/El_Aaiun"},
{"Greenwich Standard Time", "GH", "Africa/Accra"},
{"Greenwich Standard Time", "GM", "Africa/Banjul"},
{"Greenwich Standard Time", "GN", "Africa/Conakry"},
{"Greenwich Standard Time", "GW", "Africa/Bissau"},
{"Greenwich Standard Time", "IS", "Atlantic/Reykjavik"},
{"Greenwich Standard Time", "LR", "Africa/Monrovia"},
{"Greenwich Standard Time", "ML", "Africa/Bamako"},
{"Greenwich Standard Time", "MR", "Africa/Nouakchott"},
{"Greenwich Standard Time", "SH", "Atlantic/St_Helena"},
{"Greenwich Standard Time", "SL", "Africa/Freetown"},
{"Greenwich Standard Time", "SN", "Africa/Dakar"},
{"Greenwich Standard Time", "ST", "Africa/Sao_Tome"},
{"Greenwich Standard Time", "TG", "Africa/Lome"},
{"W. Europe Standard Time", "001", "Europe/Berlin"},
{"W. Europe Standard Time", "AD", "Europe/Andorra"},
{"W. Europe Standard Time", "AT", "Europe/Vienna"},
{"W. Europe Standard Time", "CH", "Europe/Zurich"},
{"W. Europe Standard Time", "DE", "Europe/Berlin"},
{"W. Europe Standard Time", "DE", "Europe/Busingen"},
{"W. Europe Standard Time", "GI", "Europe/Gibraltar"},
{"W. Europe Standard Time", "IT", "Europe/Rome"},
{"W. Europe Standard Time", "LI", "Europe/Vaduz"},
{"W. Europe Standard Time", "LU", "Europe/Luxembourg"},
{"W. Europe Standard Time", "LY", "Africa/Tripoli"},
{"W. Europe Standard Time", "MC", "Europe/Monaco"},
{"W. Europe Standard Time", "MT", "Europe/Malta"},
{"W. Europe Standard Time", "NL", "Europe/Amsterdam"},
{"W. Europe Standard Time", "NO", "Europe/Oslo"},
{"W. Europe Standard Time", "SE", "Europe/Stockholm"},
{"W. Europe Standard Time", "SJ", "Arctic/Longyearbyen"},
{"W. Europe Standard Time", "SM", "Europe/San_Marino"},
{"W. Europe Standard Time", "VA", "Europe/Vatican"},
{"Central Europe Standard Time", "001", "Europe/Budapest"},
{"Central Europe Standard Time", "AL", "Europe/Tirane"},
{"Central Europe Standard Time", "CZ", "Europe/Prague"},
{"Central Europe Standard Time", "HU", "Europe/Budapest"},
{"Central Europe Standard Time", "ME", "Europe/Podgorica"},
{"Central Europe Standard Time", "RS", "Europe/Belgrade"},
{"Central Europe Standard Time", "SI", "Europe/Ljubljana"},
{"Central Europe Standard Time", "SK", "Europe/Bratislava"},
{"Romance Standard Time", "001", "Europe/Paris"},
{"Romance Standard Time", "BE", "Europe/Brussels"},
{"Romance Standard Time", "DK", "Europe/Copenhagen"},
{"Romance Standard Time", "ES", "Europe/Madrid"},
{"Romance Standard Time", "ES", "Africa/Ceuta"},
{"Romance Standard Time", "FR", "Europe/Paris"},
{"Central European Standard Time", "001", "Europe/Warsaw"},
{"Central European Standard Time", "BA", "Europe/Sarajevo"},
{"Central European Standard Time", "HR", "Europe/Zagreb"},
{"Central European Standard Time", "MK", "Europe/Skopje"},
{"Central European Standard Time", "PL", "Europe/Warsaw"},
{"W. Central Africa Standard Time", "001", "Africa/Lagos"},
{"W. Central Africa Standard Time", "AO", "Africa/Luanda"},
{"W. Central Africa Standard Time", "BJ", "Africa/Porto-Novo"},
{"W. Central Africa Standard Time", "CD", "Africa/Kinshasa"},
{"W. Central Africa Standard Time", "CF", "Africa/Bangui"},
{"W. Central Africa Standard Time", "CG", "Africa/Brazzaville"},
{"W. Central Africa Standard Time", "CM", "Africa/Douala"},
{"W. Central Africa Standard Time", "DZ", "Africa/Algiers"},
{"W. Central Africa Standard Time", "GA", "Africa/Libreville"},
{"W. Central Africa Standard Time", "GQ", "Africa/Malabo"},
{"W. Central Africa Standard Time", "NE", "Africa/Niamey"},
{"W. Central Africa Standard Time", "NG", "Africa/Lagos"},
{"W. Central Africa Standard Time", "TD", "Africa/Ndjamena"},
{"W. Central Africa Standard Time", "TN", "Africa/Tunis"},
{"W. Central Africa Standard Time", "ZZ", "Etc/GMT-1"},
{"Namibia Standard Time", "001", "Africa/Windhoek"},
{"Namibia Standard Time", "NA", "Africa/Windhoek"},
{"GTB Standard Time", "001", "Europe/Bucharest"},
{"GTB Standard Time", "GR", "Europe/Athens"},
{"GTB Standard Time", "MD", "Europe/Chisinau"},
{"GTB Standard Time", "RO", "Europe/Bucharest"},
{"Middle East Standard Time", "001", "Asia/Beirut"},
{"Middle East Standard Time", "LB", "Asia/Beirut"},
{"Egypt Standard Time", "001", "Africa/Cairo"},
{"Egypt Standard Time", "EG", "Africa/Cairo"},
{"Egypt Standard Time", "PS", "Asia/Gaza"},
{"Egypt Standard Time", "PS", "Asia/Hebron"},
{"Syria Standard Time", "001", "Asia/Damascus"},
{"Syria Standard Time", "SY", "Asia/Damascus"},
{"E. Europe Standard Time", "001", "Asia/Nicosia"},
{"E. Europe Standard Time", "CY", "Asia/Nicosia"},
{"South Africa Standard Time", "001", "Africa/Johannesburg"},
{"South Africa Standard Time", "BI", "Africa/Bujumbura"},
{"South Africa Standard Time", "BW", "Africa/Gaborone"},
{"South Africa Standard Time", "CD", "Africa/Lubumbashi"},
{"South Africa Standard Time", "LS", "Africa/Maseru"},
{"South Africa Standard Time", "MW", "Africa/Blantyre"},
{"South Africa Standard Time", "MZ", "Africa/Maputo"},
{"South Africa Standard Time", "RW", "Africa/Kigali"},
{"South Africa Standard Time", "SZ", "Africa/Mbabane"},
{"South Africa Standard Time", "ZA", "Africa/Johannesburg"},
{"South Africa Standard Time", "ZM", "Africa/Lusaka"},
{"South Africa Standard Time", "ZW", "Africa/Harare"},
{"South Africa Standard Time", "ZZ", "Etc/GMT-2"},
{"FLE Standard Time", "001", "Europe/Kiev"},
{"FLE Standard Time", "AX", "Europe/Mariehamn"},
{"FLE Standard Time", "BG", "Europe/Sofia"},
{"FLE Standard Time", "EE", "Europe/Tallinn"},
{"FLE Standard Time", "FI", "Europe/Helsinki"},
{"FLE Standard Time", "LT", "Europe/Vilnius"},
{"FLE Standard Time", "LV", "Europe/Riga"},
{"FLE Standard Time", "UA", "Europe/Kiev"},
{"FLE Standard Time", "UA", "Europe/Simferopol"},
{"FLE Standard Time", "UA", "Europe/Uzhgorod"},
{"FLE Standard Time", "UA", "Europe/Zaporozhye"},
{"Turkey Standard Time", "001", "Europe/Istanbul"},
{"Turkey Standard Time", "TR", "Europe/Istanbul"},
{"Israel Standard Time", "001", "Asia/Jerusalem"},
{"Israel Standard Time", "IL", "Asia/Jerusalem"},
{"Jordan Standard Time", "001", "Asia/Amman"},
{"Jordan Standard Time", "JO", "Asia/Amman"},
{"Arabic Standard Time", "001", "Asia/Baghdad"},
{"Arabic Standard Time", "IQ", "Asia/Baghdad"},
{"Kaliningrad Standard Time", "001", "Europe/Kaliningrad"},
{"Kaliningrad Standard Time", "BY", "Europe/Minsk"},
{"Kaliningrad Standard Time", "RU", "Europe/Kaliningrad"},
{"Arab Standard Time", "001", "Asia/Riyadh"},
{"Arab Standard Time", "BH", "Asia/Bahrain"},
{"Arab Standard Time", "KW", "Asia/Kuwait"},
{"Arab Standard Time", "QA", "Asia/Qatar"},
{"Arab Standard Time", "SA", "Asia/Riyadh"},
{"Arab Standard Time", "YE", "Asia/Aden"},
{"E. Africa Standard Time", "001", "Africa/Nairobi"},
{"E. Africa Standard Time", "AQ", "Antarctica/Syowa"},
{"E. Africa Standard Time", "DJ", "Africa/Djibouti"},
{"E. Africa Standard Time", "ER", "Africa/Asmera"},
{"E. Africa Standard Time", "ET", "Africa/Addis_Ababa"},
{"E. Africa Standard Time", "KE", "Africa/Nairobi"},
{"E. Africa Standard Time", "KM", "Indian/Comoro"},
{"E. Africa Standard Time", "MG", "Indian/Antananarivo"},
{"E. Africa Standard Time", "SD", "Africa/Khartoum"},
{"E. Africa Standard Time", "SO", "Africa/Mogadishu"},
{"E. Africa Standard Time", "SS", "Africa/Juba"},
{"E. Africa Standard Time", "TZ", "Africa/Dar_es_Salaam"},
{"E. Africa Standard Time", "UG", "Africa/Kampala"},
{"E. Africa Standard Time", "YT", "Indian/Mayotte"},
{"E. Africa Standard Time", "ZZ", "Etc/GMT-3"},
{"Iran Standard Time", "001", "Asia/Tehran"},
{"Iran Standard Time", "IR", "Asia/Tehran"},
{"Arabian Standard Time", "001", "Asia/Dubai"},
{"Arabian Standard Time", "AE", "Asia/Dubai"},
{"Arabian Standard Time", "OM", "Asia/Muscat"},
{"Arabian Standard Time", "ZZ", "Etc/GMT-4"},
{"Azerbaijan Standard Time", "001", "Asia/Baku"},
{"Azerbaijan Standard Time", "AZ", "Asia/Baku"},
{"Russian Standard Time", "001", "Europe/Moscow"},
{"Russian Standard Time", "RU", "Europe/Moscow"},
{"Russian Standard Time", "RU", "Europe/Samara"},
{"Russian Standard Time", "RU", "Europe/Volgograd"},
{"Mauritius Standard Time", "001", "Indian/Mauritius"},
{"Mauritius Standard Time", "MU", "Indian/Mauritius"},
{"Mauritius Standard Time", "RE", "Indian/Reunion"},
{"Mauritius Standard Time", "SC", "Indian/Mahe"},
{"Georgian Standard Time", "001", "Asia/Tbilisi"},
{"Georgian Standard Time", "GE", "Asia/Tbilisi"},
{"Caucasus Standard Time", "001", "Asia/Yerevan"},
{"Caucasus Standard Time", "AM", "Asia/Yerevan"},
{"Afghanistan Standard Time", "001", "Asia/Kabul"},
{"Afghanistan Standard Time", "AF", "Asia/Kabul"},
{"Pakistan Standard Time", "001", "Asia/Karachi"},
{"Pakistan Standard Time", "PK", "Asia/Karachi"},
{"West Asia Standard Time", "001", "Asia/Tashkent"},
{"West Asia Standard Time", "AQ", "Antarctica/Mawson"},
{"West Asia Standard Time", "KZ", "Asia/Oral"},
{"West Asia Standard Time", "KZ", "Asia/Aqtau"},
{"West Asia Standard Time", "KZ", "Asia/Aqtobe"},
{"West Asia Standard Time", "MV", "Indian/Maldives"},
{"West Asia Standard Time", "TF", "Indian/Kerguelen"},
{"West Asia Standard Time", "TJ", "Asia/Dushanbe"},
{"West Asia Standard Time", "TM", "Asia/Ashgabat"},
{"West Asia Standard Time", "UZ", "Asia/Tashkent"},
{"West Asia Standard Time", "UZ", "Asia/Samarkand"},
{"West Asia Standard Time", "ZZ", "Etc/GMT-5"},
{"India Standard Time", "001", "Asia/Calcutta"},
{"India Standard Time", "IN", "Asia/Calcutta"},
{"Sri Lanka Standard Time", "001", "Asia/Colombo"},
{"Sri Lanka Standard Time", "LK", "Asia/Colombo"},
{"Nepal Standard Time", "001", "Asia/Katmandu"},
{"Nepal Standard Time", "NP", "Asia/Katmandu"},
{"Central Asia Standard Time", "001", "Asia/Almaty"},
{"Central Asia Standard Time", "AQ", "Antarctica/Vostok"},
{"Central Asia Standard Time", "IO", "Indian/Chagos"},
{"Central Asia Standard Time", "KG", "Asia/Bishkek"},
{"Central Asia Standard Time", "KZ", "Asia/Almaty"},
{"Central Asia Standard Time", "KZ", "Asia/Qyzylorda"},
{"Central Asia Standard Time", "ZZ", "Etc/GMT-6"},
{"Bangladesh Standard Time", "001", "Asia/Dhaka"},
{"Bangladesh Standard Time", "BD", "Asia/Dhaka"},
{"Bangladesh Standard Time", "BT", "Asia/Thimphu"},
{"Ekaterinburg Standard Time", "001", "Asia/Yekaterinburg"},
{"Ekaterinburg Standard Time", "RU", "Asia/Yekaterinburg"},
{"Myanmar Standard Time", "001", "Asia/Rangoon"},
{"Myanmar Standard Time", "CC", "Indian/Cocos"},
{"Myanmar Standard Time", "MM", "Asia/Rangoon"},
{"SE Asia Standard Time", "001", "Asia/Bangkok"},
{"SE Asia Standard Time", "AQ", "Antarctica/Davis"},
{"SE Asia Standard Time", "CX", "Indian/Christmas"},
{"SE Asia Standard Time", "ID", "Asia/Jakarta"},
{"SE Asia Standard Time", "ID", "Asia/Pontianak"},
{"SE Asia Standard Time", "KH", "Asia/Phnom_Penh"},
{"SE Asia Standard Time", "LA", "Asia/Vientiane"},
{"SE Asia Standard Time", "MN", "Asia/Hovd"},
{"SE Asia Standard Time", "TH", "Asia/Bangkok"},
{"SE Asia Standard Time", "VN", "Asia/Saigon"},
{"SE Asia Standard Time", "ZZ", "Etc/GMT-7"},
{"N. Central Asia Standard Time", "001", "Asia/Novosibirsk"},
{"N. Central Asia Standard Time", "RU", "Asia/Novosibirsk"},
{"N. Central Asia Standard Time", "RU", "Asia/Novokuznetsk"},
{"N. Central Asia Standard Time", "RU", "Asia/Omsk"},
{"China Standard Time", "001", "Asia/Shanghai"},
{"China Standard Time", "CN", "Asia/Shanghai"},
{"China Standard Time", "CN", "Asia/Chongqing"},
{"China Standard Time", "CN", "Asia/Harbin"},
{"China Standard Time", "CN", "Asia/Kashgar"},
{"China Standard Time", "CN", "Asia/Urumqi"},
{"China Standard Time", "HK", "Asia/Hong_Kong"},
{"China Standard Time", "MO", "Asia/Macau"},
{"North Asia Standard Time", "001", "Asia/Krasnoyarsk"},
{"North Asia Standard Time", "RU", "Asia/Krasnoyarsk"},
{"Singapore Standard Time", "001", "Asia/Singapore"},
{"Singapore Standard Time", "BN", "Asia/Brunei"},
{"Singapore Standard Time", "ID", "Asia/Makassar"},
{"Singapore Standard Time", "MY", "Asia/Kuala_Lumpur"},
{"Singapore Standard Time", "MY", "Asia/Kuching"},
{"Singapore Standard Time", "PH", "Asia/Manila"},
{"Singapore Standard Time", "SG", "Asia/Singapore"},
{"Singapore Standard Time", "ZZ", "Etc/GMT-8"},
{"W. Australia Standard Time", "001", "Australia/Perth"},
{"W. Australia Standard Time", "AQ", "Antarctica/Casey"},
{"W. Australia Standard Time", "AU", "Australia/Perth"},
{"Taipei Standard Time", "001", "Asia/Taipei"},
{"Taipei Standard Time", "TW", "Asia/Taipei"},
{"Ulaanbaatar Standard Time", "001", "Asia/Ulaanbaatar"},
{"Ulaanbaatar Standard Time", "MN", "Asia/Ulaanbaatar"},
{"Ulaanbaatar Standard Time", "MN", "Asia/Choibalsan"},
{"North Asia East Standard Time", "001", "Asia/Irkutsk"},
{"North Asia East Standard Time", "RU", "Asia/Irkutsk"},
{"Tokyo Standard Time", "001", "Asia/Tokyo"},
{"Tokyo Standard Time", "ID", "Asia/Jayapura"},
{"Tokyo Standard Time", "JP", "Asia/Tokyo"},
{"Tokyo Standard Time", "PW", "Pacific/Palau"},
{"Tokyo Standard Time", "TL", "Asia/Dili"},
{"Tokyo Standard Time", "ZZ", "Etc/GMT-9"},
{"Korea Standard Time", "001", "Asia/Seoul"},
{"Korea Standard Time", "KP", "Asia/Pyongyang"},
{"Korea Standard Time", "KR", "Asia/Seoul"},
{"Cen. Australia Standard Time", "001", "Australia/Adelaide"},
{"Cen. Australia Standard Time", "AU", "Australia/Adelaide"},
{"Cen. Australia Standard Time", "AU", "Australia/Broken_Hill"},
{"AUS Central Standard Time", "001", "Australia/Darwin"},
{"AUS Central Standard Time", "AU", "Australia/Darwin"},
{"E. Australia Standard Time", "001", "Australia/Brisbane"},
{"E. Australia Standard Time", "AU", "Australia/Brisbane"},
{"E. Australia Standard Time", "AU", "Australia/Lindeman"},
{"AUS Eastern Standard Time", "001", "Australia/Sydney"},
{"AUS Eastern Standard Time", "AU", "Australia/Sydney"},
{"AUS Eastern Standard Time", "AU", "Australia/Melbourne"},
{"West Pacific Standard Time", "001", "Pacific/Port_Moresby"},
{"West Pacific Standard Time", "AQ", "Antarctica/DumontDUrville"},
{"West Pacific Standard Time", "FM", "Pacific/Truk"},
{"West Pacific Standard Time", "GU", "Pacific/Guam"},
{"West Pacific Standard Time", "MP", "Pacific/Saipan"},
{"West Pacific Standard Time", "PG", "Pacific/Port_Moresby"},
{"West Pacific Standard Time", "ZZ", "Etc/GMT-10"},
{"Tasmania Standard Time", "001", "Australia/Hobart"},
{"Tasmania Standard Time", "AU", "Australia/Hobart"},
{"Tasmania Standard Time", "AU", "Australia/Currie"},
{"Yakutsk Standard Time", "001", "Asia/Yakutsk"},
{"Yakutsk Standard Time", "RU", "Asia/Yakutsk"},
{"Yakutsk Standard Time", "RU", "Asia/Khandyga"},
{"Central Pacific Standard Time", "001", "Pacific/Guadalcanal"},
{"Central Pacific Standard Time", "AQ", "Antarctica/Macquarie"},
{"Central Pacific Standard Time", "FM", "Pacific/Ponape"},
{"Central Pacific Standard Time", "FM", "Pacific/Kosrae"},
{"Central Pacific Standard Time", "NC", "Pacific/Noumea"},
{"Central Pacific Standard Time", "SB", "Pacific/Guadalcanal"},
{"Central Pacific Standard Time", "VU", "Pacific/Efate"},
{"Central Pacific Standard Time", "ZZ", "Etc/GMT-11"},
{"Vladivostok Standard Time", "001", "Asia/Vladivostok"},
{"Vladivostok Standard Time", "RU", "Asia/Vladivostok"},
{"Vladivostok Standard Time", "RU", "Asia/Sakhalin"},
{"Vladivostok Standard Time", "RU", "Asia/Ust-Nera"},
{"New Zealand Standard Time", "001", "Pacific/Auckland"},
{"New Zealand Standard Time", "AQ", "Antarctica/South_Pole"},
{"New Zealand Standard Time", "AQ", "Antarctica/McMurdo"},
{"New Zealand Standard Time", "NZ", "Pacific/Auckland"},
{"UTC+12", "001", "Etc/GMT-12"},
{"UTC+12", "KI", "Pacific/Tarawa"},
{"UTC+12", "MH", "Pacific/Majuro"},
{"UTC+12", "MH", "Pacific/Kwajalein"},
{"UTC+12", "NR", "Pacific/Nauru"},
{"UTC+12", "TV", "Pacific/Funafuti"},
{"UTC+12", "UM", "Pacific/Wake"},
{"UTC+12", "WF", "Pacific/Wallis"},
{"UTC+12", "ZZ", "Etc/GMT-12"},
{"Fiji Standard Time", "001", "Pacific/Fiji"},
{"Fiji Standard Time", "FJ", "Pacific/Fiji"},
{"Magadan Standard Time", "001", "Asia/Magadan"},
{"Magadan Standard Time", "RU", "Asia/Magadan"},
{"Magadan Standard Time", "RU", "Asia/Anadyr"},
{"Magadan Standard Time", "RU", "Asia/Kamchatka"},
{"Tonga Standard Time", "001", "Pacific/Tongatapu"},
{"Tonga Standard Time", "KI", "Pacific/Enderbury"},
{"Tonga Standard Time", "TK", "Pacific/Fakaofo"},
{"Tonga Standard Time", "TO", "Pacific/Tongatapu"},
{"Tonga Standard Time", "ZZ", "Etc/GMT-13"},
{"Samoa Standard Time", "001", "Pacific/Apia"},
{"Samoa Standard Time", "WS", "Pacific/Apia"}
};
const size_t tz_unicode_map_size =  435 ;

