set(CPACK_PACKAGE_VENDOR "EPAM Systems")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Crossplatform library for date time manipulation and locale convertations")
set(CPACK_GENERATOR "TGZ")
install(TARGETS ${PROJECT_NAME} ARCHIVE DESTINATION lib)
install(FILES ${CMAKE_SOURCE_DIR}/include/libdt/dt.h DESTINATION include/libdt)
install(FILES ${CMAKE_SOURCE_DIR}/include/libdt/dt_posix.h DESTINATION include/libdt)
install(FILES ${CMAKE_SOURCE_DIR}/include/libdt/dt_convert.h DESTINATION include/libdt)
install(FILES ${CMAKE_SOURCE_DIR}/include/libdt/dt_types.h DESTINATION include/libdt)
if(DOXYGEN_FOUND)
    install(DIRECTORY ${CMAKE_SOURCE_DIR}/doc DESTINATION share/doc/libdt)
endif()
include(CPack)
